import { cn } from "@renderer/utils/cn";
import { IconProps, IconRegistry } from "./icons.types";
import {
  Mailbox,
  Code,
  Sparkle,
  HardDrive,
  Zap,
  Lightbulb,
  Heart,
  Crown,
  User,
  Camera,
  Music,
  Palette,
  Book,
  Coffee,
  Gamepad2,
  Briefcase,
  Rocket,
  Target,
  Star,
  Shield,
  Globe,
  Phone,
  MessageCircle,
  Search,
  Settings,
  Download,
  Upload,
  Clock,
  Calendar,
  Bell,
  Trophy,
  Gift,
  Smile,
  Image,
  Brain,
  Headphones,
  Brush,
  Mountain,
  Laptop,
  Key,
  Flag,
  Compass,
  Flame,
  Leaf,
  Hammer,
  Wrench,
  Scissors,
  Paintbrush,
  Pencil,
  Pen,
  Feather,
  Glasses,
  Watch,
  Gem,
  Diamond,
  Flower2,
  Trees,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  Car,
  Plane,
  Bike,
  Fish,
  Dog,
  Cat,
  Pizza,
  Dumbbell,
  Telescope,
  Mic,
  Guitar,
  Lock,
  Unlock,
  Home,
  Building,
} from "lucide-react";

export const personasIconsRegistry: IconRegistry = {
  mailbox: Mailbox,
  code: Code,
  sparkle: Sparkle,
  "hard-drive": HardDrive,
  user: User,
  zap: Zap,
  lightbulb: Lightbulb,
  heart: Heart,
  crown: Crown,
  camera: Camera,
  music: Music,
  palette: Palette,
  book: Book,
  coffee: Coffee,
  "gamepad-2": Gamepad2,
  briefcase: Briefcase,
  rocket: Rocket,
  target: Target,
  star: Star,
  shield: Shield,
  globe: Globe,
  phone: Phone,
  "message-circle": MessageCircle,
  search: Search,
  settings: Settings,
  download: Download,
  upload: Upload,
  clock: Clock,
  calendar: Calendar,
  bell: Bell,
  trophy: Trophy,
  gift: Gift,
  smile: Smile,
  image: Image,
  brain: Brain,
  headphones: Headphones,
  brush: Brush,
  mountain: Mountain,
  laptop: Laptop,
  key: Key,
  flag: Flag,
  compass: Compass,
  flame: Flame,
  leaf: Leaf,
  hammer: Hammer,
  wrench: Wrench,
  scissors: Scissors,
  paintbrush: Paintbrush,
  pencil: Pencil,
  pen: Pen,
  feather: Feather,
  glasses: Glasses,
  watch: Watch,
  gem: Gem,
  diamond: Diamond,
  flower2: Flower2,
  trees: Trees,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  umbrella: Umbrella,
  car: Car,
  plane: Plane,
  bike: Bike,
  fish: Fish,
  dog: Dog,
  cat: Cat,
  pizza: Pizza,
  dumbbell: Dumbbell,
  telescope: Telescope,
  microphone: Mic,
  guitar: Guitar,
  lock: Lock,
  unlock: Unlock,
  home: Home,
  building: Building,
};

const getPersonaIcon = (icon: keyof typeof personasIconsRegistry | null) => {
  if (!icon) return personasIconsRegistry["sparkle"];
  return personasIconsRegistry[icon] || personasIconsRegistry["sparkle"];
};

export const PersonaIcon = ({
  icon,
  className,
  ...props
}: IconProps & { icon: keyof typeof personasIconsRegistry | null }) => {
  const Icon = getPersonaIcon(icon);

  return <Icon className={cn(className)} {...props} />;
};
