// TODO: Add more languages
export const languages = [
  { name: "Auto", code: "auto", flag: "🌐" },
  { name: "Arabic", code: "ar", flag: "🇸🇦" },
  { name: "Chinese", code: "zh", flag: "🇨🇳" },
  { name: "Dutch", code: "nl", flag: "🇳🇱" },
  { name: "English", code: "en", flag: "🇬🇧" },
  { name: "Finnish", code: "fi", flag: "🇫🇮" },
  { name: "French", code: "fr", flag: "🇫🇷" },
  { name: "German", code: "de", flag: "🇩🇪" },
  { name: "Hindi", code: "hi", flag: "🇮🇳" },
  { name: "Italian", code: "it", flag: "🇮🇹" },
  { name: "Japanese", code: "ja", flag: "🇯🇵" },
  { name: "Korean", code: "ko", flag: "🇰🇷" },
  { name: "Norwegian", code: "no", flag: "🇳🇴" },
  { name: "Polish", code: "pl", flag: "🇵🇱" },
  { name: "Portuguese", code: "pt", flag: "🇵🇹" },
  { name: "Punjabi (Eastern)", code: "pa", flag: "🇮🇳" },
  { name: "Romanian", code: "ro", flag: "🇷🇴" },
  { name: "Russian", code: "ru", flag: "🇷🇺" },
  { name: "Spanish", code: "es", flag: "🇪🇸" },
  { name: "Swedish", code: "sv", flag: "🇸🇪" },
  { name: "Turkish", code: "tr", flag: "🇹🇷" },
  { name: "Ukrainian", code: "uk", flag: "🇺🇦" },
  { name: "Vietnamese", code: "vi", flag: "🇻🇳" },
];
